Build keretrendszer és CI beüzemelése
BME-MIT-IET/iet-hf2021-iglue pull request #5
Opened 2021-05-06 19:07 UTC by timiant

Konfiguráltam a projektet  build keretrendszerrel. Build keretrendszernek Gradle-t használok. Készítettem egy Github Actions workflow-t is.

2021-05-06 19:14 UTC, timiant commented
A CI is sikeresen lefutott, lásd az Actions tabon.

2021-05-06 19:21 UTC, timiant commented
Szia Tomi, elkészítettem a gradle-t és CI-t. Megkérnélek, hogy nézd át és ha rendben találod akkor zárjuk le a #1 Issue-t.
@tamas-visy

2021-05-06 20:55 UTC, tamas-visy requested changes
A .idea/sonarlint mappában lévő fájlokra szerintem nincs szükség. Kérlek frissítsd a .gitignore-t, és ellenőrizd, hogy ezek ne kerüljenek feltöltésre.

A két másik megjegyzésem csak komment jellegű.

2021-05-06 20:55 UTC, tamas-visy commented on src/test/java/IglueTest.java
> +public class IglueTest {
Érdemes lenne további teszteket hozzáadni.

2021-05-06 20:55 UTC, tamas-visy commented on src/Skeleton/Skeleton.java
> -//package Skeleton;
A kommentezett kódra már nincs szükség, de ez nem érinti Build + CI-t.
Érdemes lett volna más pull request-ben törölni.

2021-05-06 20:55 UTC, tamas-visy commented on .gitignore
> +
A .idea/sonarlint almappát hozzá kellene adni a .gitignore-hoz.

2021-05-07 07:34 UTC, timiant reviewed
Javítottam a gitignore-t, kiszedtem a SonarLint-el kapcsolatos fájlokat. Egyezzünk meg abban, hogy az Issue #1 -et még nem zárjuk le, egy külön PRben folytatom a tesztek írását.

2021-05-07 07:34 UTC, timiant commented on .gitignore
> +
Igazad van, javítom

2021-05-07 07:36 UTC, timiant commented on src/test/java/IglueTest.java
> +public class IglueTest {
Egy külön PRben készítem el a teszteket

2021-05-07 08:32 UTC, tamas-visy approved these changes
A kért módosítások (gitignore update és fájlok eltávolítása) megtörténtek.

2021-05-07 13:50 UTC, merged